# FUENTE: https://github.com/niltoncsr/rosalind/blob/master/complementing-a-strand-of-dna.py
s = 'AATTAAAAAAAAGCGCGGGGCACCATATTGAGGCTCAACGGCTGTAGGACGTTCAGATCCATGATTGTGCCATGATCTCTATAATAAATATACGCATAATGCTGGTCGTCACATTTAGCGAATGTCGGTACGTGACGTCTCGTTTCTAAGGAGACGGATATGATAACCCGTCTGGCGATACGCCACAAACTCTTATCTAGATACCACCTGTTTATAGTGCCACATAGGGTTACAGTCTAGCATAGATATATCCCCTCTGCGTATTTTACTTCCCACCCGAACTATGCCCCCGTGAAGGGGCTCTGCAGTGTGGTGGTGGGAAGCCAGAAAAGTCACGACACCCATCATCGTTGAAAACCAGGCCACCGAGGATTGCCACAGTCTGGACACTGTTTATACCAGCGTTGGCCGGATCCGCACGATATTCTCGAAATCAATAATGACCCCGCCTGCGCGCCGGAAGGATATACCGGTCAGTTAGGATAAAGAGCGAGTCGGATAGCCCACAACTAACGATTTTTGCCCGTCAGGACCGATTGGGCTTAACAGGTCTCACGTAATCAGCAGGATGCCTTAATAACACAGATAAACGCTCGGCGCCTGACTTATGGACAAGAATAATTCATATCAGTATTGGGGGGCGTAACAGCGAATATGGAACCTTCCCCCGATGACCAGCGCGGACGTTGAGCGTTTGGACTGTCTGGGTTGTTCAGCAATGGTATCTTCTTCAACACATGCAAGCAGCCGGCTTGGAGAGCGTAGATCTCGATCGCATCCCATCTGTGCCCTATCGTCGTACTGGGCCGATACGTTCTCACCGTTTTAGTGTTTA'
sc = ''

for nt in s:
	if nt == 'A': nt = 'T'
	elif nt == 'T': nt = 'A'
	elif nt == 'G': nt = 'C'
	elif nt == 'C': nt = 'G'
	sc += nt

i_sc = sc[::-1]
print(i_sc)
